name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Build
      run: |
        npm ci
        npm run build
        cp -r ./html ./dist/
        cp -r ./assets ./dist/assets
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag parker1331/vk-jam-front:latest

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push tag to Docker Hub
      run: docker push parker1331/vk-jam-front:latest
